### ISSUE TITLE
Bug when supplying a 1D array as event times

### ISSUE THREAD

**Issue by guidomeijer** [JorritMontijn/zetapy#1]
Thanks for providing this amazing statistical test with python code! There currently is a bug in the code that prevents inputting a 1D array as matEventTimes while the docstring states that it should be possible. To fix it you have to change lines 100-103 to the following:
```
    if len(matEventTimes.shape) > 1:
       boolStopSupplied = True
       if np.shape(matEventTimes)[1] > 2:
           matEventTimes = np.transpose(matEventTimes)
    else:
        matEventTimes = np.vstack((matEventTimes, np.zeros(matEventTimes.shape))).T
```
Cheers, Guido

**Comment by heimel** [comment]
Hey Guido,

Thanks a lot for detecting the bug and fixing it! I have uploaded your
bugfix.

The python code may contain some more bugs. Python is not my native
language. I have just tested the python translation on the examples
supplied with the matlab code. If you find more, perhaps Jorrit can also
make you a contributor if you like.

Have a good weekend,
Alexander

**Comment by guidomeijer** [comment]
Thanks for pushing the fix. Yes I'd be happy to help improve the python code! I already found a couple of other bugs.
