### ISSUE TITLE
pip install zetapy doesn't install whole package

### ISSUE THREAD

**Issue by RejwanSalih** [JorritMontijn/zetapy#9]
Hi, 

I install zetapy with "pip install zetapy" but notice that it doesn't install the "legacy" folder as well. 

I will install this manually, but I thought I would give a heads up!

Kind regards,
Rejwan

**Comment by JorritMontijn** [comment]
Yes, I see you're correct. Thank you for your message, we'll look into it!

**Comment by guidomeijer** [comment]
This was fixed in a new release. You can update to the latest version like this `pip install zetapy -U`
